# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
env:
#  - CONDA_PYTHON_VERSION=2.7
  - CONDA_PYTHON_VERSION=3.6

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  - conda config --add channels conda-forge
  - conda config --add channels SimpleITK
  - conda config --add channels mjirik
  # download training data
  #    - mkdir -p ~/data/medical/orig
  #    - wget http://home.zcu.cz/~mjirik/lisa/sample-data/Io3dP_sample_data.zip
  #    - unzip -d ~/data/medical/orig/ Io3dP_sample_data.zip
  # command to install dependencies
  - conda create --yes -n travis pip nose python=$CONDA_PYTHON_VERSION Io3dP SimpleITK
  - source activate travis
  - export PYTHON=`which python`
  - julia -e 'using Pkg; Pkg.build("PyCall")'

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
